name: sbt_encrypt
description: SBT encryt
version: 0.1.3
homepage: https://github.com/stonega/sbt_encrypt

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  argon2: ^1.0.1
  cryptography: ^2.0.5
  encrypt: ^5.0.1
