name: aes_dart
description: Aes dart
version: 0.1.2

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  cryptography: ^2.0.5
  encrypt: ^5.0.1
